### ISSUE TITLE
Add Theo as a collaborator on the repo

### ISSUE THREAD

**Issue by TheoPannetier** [joshwlambert/DAISIEprep#1]
Thank you :) 

(I'm sure you know this but just in case -> [Inviting collaborators to a personal repo](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository))

**Comment by joshwlambert** [comment]
Added @TheoPannetier as collaborator
