### ISSUE TITLE
Load files in tutorial - is there a better way?

### ISSUE THREAD

**Issue by luislvalente** [joshwlambert/DAISIEprep#38]
At the moment, the tutorial uses a non-optimal way to locate and load files, e.g.:

```
plant_phylo <- readRDS(
  file = system.file("extdata", "plant_phylo.rds", package = "DAISIEprep")
)
```

This might confuse the user. I could not find a good way to do this. Ideally we would directly load a file from the package but without having to use this complicated code.

**Comment by Neves-P** [comment]
This file is not actually the package (at least under `inst/extdata`), so this line to me returns 

``` r
Error in gzfile(file, "rb") : cannot open the connection
``` 

It might be easier to include these files as package data, i.e., replacing lines like `saveRDS(columbiformes_phylod, file = "inst/extdata/columbiformes_phylod.rds")` with `usethis::use_data(columbiformes_phylod)` in `data-raw/columbiformes_phylod.R` and then documenting the resulting `.rda` data object in `R/data.R`. I'm guessing there is a reason to go with `extdata/` instead?

**Comment by luislvalente** [comment]
thanks @Neves-P ! I didn't realise that the file was not in the package because the render was working fine in my computer (I had forgotten to install the package again locally after the changes). now that has been fixed and the file should be included. 

@joshwlambert - could be worth checking Pedro's suggestions?

**Comment by joshwlambert** [comment]
I don't remember why we originally put this data into `inst/extdata`. I have do some git archeology and see if the commit messages give any info on this. I've tested out whether it is possible to use `data()` in the tutorial vignette in eb7ea7b19d3a9b12e292d6d9116a9a1d55f78668 and it is indeed possible. 

I'm going to look into what the benefits/downsides of using `inst/extdata` versus `data/` and then I will make the change in a separate PR to #42. Being more user-friendly is one benefit of using `data/`.

**Comment by joshwlambert** [comment]
Files have now been moved to `data/` and can be loaded with `data()`. The tutorial vignette is updated to simplify loading data. All changes have been made in PR #42.
