### ISSUE TITLE
Add logo to tutorial

### ISSUE THREAD

**Issue by luislvalente** [joshwlambert/DAISIEprep#39]
In the new tutorial, after changing from quarto back to markdown, I could no longer load the logo image. The image is located in /man/figures/logo.png

It would be nice to add it back so that the logo appears in the rendered version of the tutorial, but I could not get it to work

**Comment by Neves-P** [comment]
I think, but @joshwlambert knows this much better than me, that the logo as in https://joshwlambert.github.io/DAISIEprep/articles/Tutorial.html will appear as part of the layout of the `pkgdown` website and not if you're rendering it from `Knitting` via RStudio or ` knitr:knit()`. So I think once the PR is merged the website should automatically update and the logo should be there 😄

**Comment by luislvalente** [comment]
thanks! I meant including the logo also in the tutorial

**Comment by joshwlambert** [comment]
I've added the logo to the tutorial in PR #42 (e919a7c2151f0f0d8ff20e5546fc177ec56abfb2) based on the what you initially added to the quarto tutorial @luislvalente (https://github.com/joshwlambert/DAISIEprep/blob/improve_tutorial/vignettes/NewTutorial.qmd). 

@Neves-P is right that pkgdown automatically puts the logo in the top-right corner of the vignettes, but for this specific vignette I don't think it hurts to have it embedded in the document. 

I've not centred the image as you did it last time @luislvalente as it's not possible with markdown and I don't think it's worth the effort of messing around with CSS or HTML for this.
