### ISSUE TITLE
Draft ASR vignette introduction section

### ISSUE THREAD

**Issue by TheoPannetier** [joshwlambert/DAISIEprep#4]
This section should explain the reader why it is relevant to perform ASR for DAISIE data preparation.
It should also describe an overview of the examples that are going to be covered through the vignette.

**Comment by TheoPannetier** [comment]
The whole exercise might be a bit more convoluted than I anticipated; the assumptions of DAISIE do not necessarily match the processes modelled by DEC and SSE models. It would be good to remind of this in the intro (or a concluding section?).
Developping a DAISIE-based ASR routine would probably be an appropriate solution but it's a challenging problem. For now, I'll focus on making the simple examples with DEC / SSE ASRs and come write the introduction later.

**Comment by joshwlambert** [comment]
@TheoPannetier this is not really a problem, the assumptions of DAISIE are used in a different algorithm in DAISIEprep by setting `extraction_method = "min"` in `extract_island_species()`. It is a good point you make that the differences between the assumptions of DAISIE and the ASR method of choice should be realised and explained in the vignette.

**Comment by TheoPannetier** [comment]
Oh right, I hadn't realised that `"min"` was doing just that. Brilliant then, if anything I'm more aware now of the conceptual differences between DAISIE and SSE/DEC models.

**Comment by TheoPannetier** [comment]
TODO: discuss why it's not that simple to do ASR with DAISIE, show an example of a tricky tree (NE clade nested within E clade) where the "min" algorithm returns counterintuitive results.

**Comment by TheoPannetier** [comment]
Finished intro draft, ready for review / PR
